name: unit-tests
on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        go: ['1.19.x']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Src Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make build

      - name: Check
        env:
          GOPROXY: "https://proxy.golang.org"
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@2023.1.1
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          hash -r
          make check

      - name: Tests
        env:
          GOPROXY: "https://proxy.golang.org"
          CI: true
        run: make test
